colors:
  # Default colors
  primary:
    background: '#0f101a'
    foreground: '#67e689'

  # Normal colors
  normal:
    black:   '#181a29'
    red:     '#007700'
    green:   '#00bb00'
    yellow:  '#7fde5d'
    blue:    '#4dbd72'
    magenta: '#2e9e3e'
    cyan:    '#4ddb7c'
    white:   '#67e689'
    
  # Bright colors
  bright:
    black:   '#282a40'
    red:     '#007700'
    green:   '#00bb00'
    yellow:  '#7fde5d'
    blue:    '#4dbd72'
    magenta: '#2e9e3e'
    cyan:    '#4ddb7c'
    white:   '#57d979'
