colors:
  # Default colors
  primary:
    background: '#212121'
    foreground: '#c5c9de'

  # Normal colors
  normal:
    black:   '#181a29'
    red:     '#F07178'
    green:   '#cdea9f'
    yellow:  '#ffd47e'
    blue:    '#93bbff'
    magenta: '#d3a7ee'
    cyan:    '#98e4ff'
    white:   '#bfd5de'

  # Bright colors
  bright:
    black:   '#282a40'
    red:     '#eb7f84'
    green:   '#e0ffad'
    yellow:  '#ffee7e'
    blue:    '#a3c5ff'
    magenta: '#d6afed'
    cyan:    '#98fffd'
    white:   '#d1e5ed'
