colors:
  # Default colors
  primary:
    background: '#1f1d29'
    foreground: '#ffffff'

  # Normal colors
  normal:
    black:   '#403c58'
    red:     '#ea6f91'
    green:   '#9bced7'
    yellow:  '#f1ca93'
    blue:    '#34738e'
    magenta: '#c3a5e6'
    cyan:    '#eabbb9'
    white:   '#faebd7'

  # Bright colors
  bright:
    black:   '#6f6e85'
    red:     '#ea6f91'
    green:   '#9bced7'
    yellow:  '#f1ca93'
    blue:    '#34738e'
    magenta: '#c3a5e6'
    cyan:    '#eabbb9'
    white:   '#ffffff'
